export enum ApplicationFeature {
  DUAL_SCREEN = 'dual_screen',
  SHARE_EMBED = 'share_embed',
  DOWNLOAD = 'download',
  BUMPER = 'bumper',
  NAVIGATION = 'navaigation',
  TRANSCRIPT = 'transcript',
  PLAYLIST = 'playlist',
  SKIP = 'skip',
  RELATED = 'related',
  CALL_TO_ACTION = 'call_to_action',
  HOTSPOPT = 'hotspot',
  QUIZ = 'quiz',
  UI = 'ui',
  DETECT_AD_BLOCK = 'detect_ad_block',
  REELS = 'reels_player',
  EAD = 'extended_audio_description',
  ADVANCED_CAPTIONS = 'advanced_captions',
  CAPTIONS = 'captions',
  AUDION_TRACKS = 'audio_tracks'
}
