// EventVar 1 in kava server

export enum ButtonType {
  View = 'View',
  Unknown = 'Unknown',
  Toggle = 'Toggle',
  Thumbnail = 'Thumbnail',
  Share = 'Share',
  Search = 'Search',
  Schedule = 'Schedule',
  Save = 'Save',
  Registration = 'Registration',
  Register = 'Register',
  Particpate = 'Particpate',
  Open = 'Open',
  Navigate = 'Navigate',
  Menu = 'Menu',
  Login = 'Login',
  Load = 'Load',
  List = 'List',
  Link = 'Link',
  Launch = 'Launch',
  Invite = 'Invite',
  Insert = 'Insert',
  Filter = 'Filter',
  Export = 'Export',
  Expand = 'Expand',
  Error = 'Error',
  Edit = 'Edit',
  Download = 'Download',
  Delete = 'Delete',
  Custom = 'Custom',
  Create = 'Create',
  Collapse = 'Collapse',
  Close = 'Close',
  Choose = 'Choose',
  Browse = 'Browse',
  Analytics = 'Analytics',
  Admin = 'Admin',
}